workflows:
  android-release:
    name: Android release

    environment:
      flutter: 3.47.4

    scripts:
      - name: Get Flutter packages
        script: |
          cd mobile-app
          flutter pub get

      - name: Analyze
        script: |
          cd mobile-app
          flutter analyze

      - name: Test
        script: |
          cd mobile-app
          flutter test

      - name: Build APK
        script: |
          cd mobile-app
          flutter build apk --release --dart-define=API_BASE_URL=$API_BASE_URL

    artifacts:
      - mobile-app/build/app/outputs/flutter-apk/app-release.apk
