<?php
namespace App\Services;
use App\Models\{User,Role}; use Illuminate\Support\Facades\Hash; use Illuminate\Support\Str; use Illuminate\Validation\ValidationException; use Tymon\JWTAuth\Facades\JWTAuth;
class AuthService { public function __construct(private OtpProvider $otp) {}
 public function register(array $d): array { $u=User::create(['id'=>(string)Str::uuid(),'name'=>$d['name'],'phone'=>$d['phone'],'email'=>$d['email']??null,'password_hash'=>Hash::make($d['password']),'status'=>'PENDING_VERIFICATION']); $u->roles()->attach(Role::where('name','REGISTERED_USER')->value('id')); $code=(string)random_int(100000,999999); \DB::table('verification_tokens')->insert(['user_id'=>$u->id,'token_hash'=>Hash::make($code),'expires_at'=>now()->addHours(24),'created_at'=>now(),'updated_at'=>now()]); $this->otp->send($u->phone,$code); return ['user'=>$u,'development_otp'=>app()->environment('local','testing')?$code:null]; }
 public function login(string $phone,string $password): array { $u=User::where('phone',$phone)->first(); if(!$u||!Hash::check($password,$u->password_hash)||$u->status!=='ACTIVE') throw ValidationException::withMessages(['credentials'=>'Invalid credentials.']); return $this->tokens($u); }
 public function tokens(User $u): array { $access=JWTAuth::fromUser($u); $refresh=(string)Str::uuid(); \DB::table('refresh_tokens')->insert(['id'=>$refresh,'user_id'=>$u->id,'token_hash'=>Hash::make($refresh),'expires_at'=>now()->addDays(30),'created_at'=>now(),'updated_at'=>now()]); return ['access_token'=>$access,'refresh_token'=>$refresh,'expires_in'=>config('jwt.ttl')*60,'user'=>$u]; }
 public function refresh(string $token): array { $row=\DB::table('refresh_tokens')->whereNull('revoked_at')->where('expires_at','>',now())->get()->first(fn($r)=>Hash::check($token,$r->token_hash)); if(!$row) throw ValidationException::withMessages(['refresh_token'=>'Invalid refresh token.']); \DB::table('refresh_tokens')->where('id',$row->id)->update(['revoked_at'=>now()]); return $this->tokens(User::findOrFail($row->user_id)); }
}
