import 'package:flutter/material.dart';import '../theme/app_theme.dart';
class GoldButton extends StatelessWidget{const GoldButton({super.key,required this.label,required this.onPressed,this.loading=false});final String label;final VoidCallback? onPressed;final bool loading;@override Widget build(BuildContext c)=>SizedBox(width:double.infinity,height:52,child:FilledButton(onPressed:loading?null:onPressed,style:FilledButton.styleFrom(backgroundColor:AppTheme.gold,foregroundColor:AppTheme.primary),child:Text(loading?'…':label)));}
class AppButton extends GoldButton{const AppButton({super.key,required super.label,required super.onPressed,super.loading});}
class AppTextField extends StatelessWidget{const AppTextField({super.key,required this.label,this.controller,this.validator,this.obscureText=false,this.maxLines=1});final String label;final TextEditingController? controller;final String? Function(String?)? validator;final bool obscureText;final int maxLines;@override Widget build(BuildContext c)=>TextFormField(controller:controller,validator:validator,obscureText:obscureText,maxLines:maxLines,decoration:InputDecoration(labelText:label));}
class LuxuryCard extends StatelessWidget{const LuxuryCard({super.key,required this.child,this.onTap});final Widget child;final VoidCallback? onTap;@override Widget build(BuildContext c)=>Card(color:Colors.white,elevation:0,child:InkWell(onTap:onTap,child:Padding(padding:const EdgeInsets.all(18),child:child)));}
class SectionHeader extends StatelessWidget{const SectionHeader(this.title,{super.key});final String title;@override Widget build(BuildContext c)=>Padding(padding:const EdgeInsets.symmetric(vertical:18),child:Text(title.toUpperCase(),style:Theme.of(c).textTheme.titleLarge));}
class Badge extends StatelessWidget{const Badge(this.label,{super.key});final String label;@override Widget build(BuildContext c)=>Chip(label:Text(label),backgroundColor:AppTheme.gold);}
class PremiumImageCard extends StatelessWidget{const PremiumImageCard({super.key,required this.title,required this.imageUrl,this.onTap});final String title,imageUrl;final VoidCallback? onTap;@override Widget build(BuildContext c)=>LuxuryCard(onTap:onTap,child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Image.network(imageUrl,height:150,width:double.infinity,fit:BoxFit.cover,errorBuilder:(_,__,___)=>const SizedBox(height:150)),Text(title,style:Theme.of(c).textTheme.titleLarge)]));}
class LoadingWidget extends StatelessWidget{const LoadingWidget({super.key});@override Widget build(BuildContext c)=>const Center(child:CircularProgressIndicator(color:AppTheme.gold));}class EmptyStateWidget extends StatelessWidget{const EmptyStateWidget({super.key,this.message='Nothing to display'});final String message;@override Widget build(BuildContext c)=>Center(child:Text(message));}class ErrorStateWidget extends StatelessWidget{const ErrorStateWidget({super.key,required this.message});final String message;@override Widget build(BuildContext c)=>Center(child:Text(message));}
